### ISSUE TITLE
Add the ability to post items (by ID) to in-game mailboxes

### ISSUE THREAD

**Issue by alkalime** [comphack/phpapi#2]
Preferably not locked down to admin accounts so we can do fun things like self-service fortune cards ;)

**Comment by Soliel** [comment]
I know it's been put on the main repo but to re-iterate: This is the PHP implementation of the servers REST API. requests should be made there, here is just to put in what the server has but this doesn't. I'll be updating this API with the new endpoints when they are implemented!
